title: Daffa Andika Zain # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an undergraduate student majoring in information systems at Universitas Pembangunan Nasional Veteran Jakarta who has an interest in fields related to Data, Business, and Design. Have good communication skills, can work with a team, have high curiosity, detail-oriented, and highly motivated to learn new skills to be able to develop my abilities and potential.  
  <br><br>
  I have some experience using Microsoft Office, Figma, Canva, draw.io, MySql, PostgreSQL, SQLserver, Python Jupyter notebook, google colab, google sheets or excel and BI Tools like Tableau, Pentaho 
  <br><br>
  <a href="https://www.linkedin.com/in/daffaandikazain/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
